name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: | 
         cd convert-tool/ 
         ./gradlew standaloneJar
         tree
    - name: Run converter
      run: | 
         mkdir Github
         echo "$PWD"
         ls -l convert-tool/app/build/libs/
         java -jar convert-tool/app/build/libs/recipes-converter-all.jar \
         --action convert --sourceAll recipes \
          --destination Github \
          --agpVersion 8.0.0-alpha10 --gradleVersion 7.5.1 --overwrite
          tree
    - name: Create release branch
      run: git checkout -b agp8.0.0
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add Github/*
        git commit --message "Prepare release"
    - name: Push new branch
      run: git push -u origin release
