name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: | 
         cd convert-tool/ 
         ./gradlew standaloneJar
         tree
    - name: Run converter
      run: | 
         mkdir Github
         java -jar ./app/build/libs/recipes-converter-all.jar \
         --action convert --sourceAll ../recipes \
          --destination ../Github \
          --agpVersion 8.0.0-alpha10 --gradleVersion 7.5.1 --overwrite
          cd ../Github
          tree
